# Generated by Django 5.2.14 on 2026-09-23 18:40

import apps.vorgang.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vorgang',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('art', models.CharField(choices=[('bauantrag', 'Bauantrag'), ('ausschreibung', 'Ausschreibung')], max_length=20)),
                ('titel', models.CharField(max_length=200)),
                ('eingereicht_von_rolle', models.CharField(choices=[('sachbearbeitung', 'Sachbearbeitung'), ('einreicher', 'Einreicher')], default='sachbearbeitung', max_length=20, verbose_name='Rolle')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('geprueft', 'Geprüft'), ('geschlossen', 'Geschlossen')], default='offen', max_length=20)),
                ('loeschfrist_am', models.DateField(blank=True, help_text="Pflicht bei Rolle 'einreicher' (#77) — wird im Service (lege_vorgang_an) erzwungen, nicht per DB-Constraint.", null=True, verbose_name='Löschfrist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vorgang',
                'verbose_name_plural': 'Vorgänge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('datei', models.FileField(upload_to=apps.vorgang.models.dokument_upload_pfad)),
                ('dateiname', models.CharField(max_length=255)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('vorlagenart', models.CharField(choices=[('lageplan', 'Lageplan'), ('grundriss', 'Grundriss'), ('schnitt', 'Schnitt'), ('ansicht', 'Ansicht'), ('baubeschreibung', 'Baubeschreibung'), ('berechnung', 'Berechnung'), ('nachweis', 'Nachweis'), ('formular', 'Formular'), ('unbekannt', 'Unbekannt')], default='unbekannt', max_length=20)),
                ('seiten', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vorgang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='vorgang.vorgang')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Befund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('regel_id', models.CharField(help_text="z. B. 'lageplan.massstab'", max_length=100)),
                ('feld', models.CharField(blank=True, max_length=100)),
                ('wert', models.TextField(blank=True)),
                ('konfidenz', models.FloatField(blank=True, null=True)),
                ('seite', models.PositiveIntegerField(blank=True, null=True)),
                ('quelle', models.JSONField(blank=True, default=dict, help_text='Fundort (Box/Textstelle), falls geliefert')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('bestaetigt', 'Bestätigt'), ('verworfen', 'Verworfen')], default='offen', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dokument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='befunde', to='vorgang.dokument')),
                ('vorgang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='befunde', to='vorgang.vorgang')),
            ],
            options={
                'verbose_name': 'Befund',
                'verbose_name_plural': 'Befunde',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vorgang',
            index=models.Index(fields=['tenant_id', 'created_at'], name='vorgang_vor_tenant__5c2fcc_idx'),
        ),
        migrations.AddIndex(
            model_name='dokument',
            index=models.Index(fields=['tenant_id', 'created_at'], name='vorgang_dok_tenant__78a470_idx'),
        ),
        migrations.AddIndex(
            model_name='befund',
            index=models.Index(fields=['tenant_id', 'created_at'], name='vorgang_bef_tenant__3872b4_idx'),
        ),
    ]
