# Generated by Django 5.1.15 on 2026-02-19 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IFCModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('ifc_file', models.FileField(upload_to='ifc_models/%Y/%m/', verbose_name='IFC Datei')),
                ('xkt_file', models.FileField(blank=True, upload_to='ifc_models/%Y/%m/', verbose_name='XKT Datei (3D Viewer)')),
                ('ifc_schema', models.CharField(blank=True, max_length=20, verbose_name='IFC Schema')),
                ('application', models.CharField(blank=True, max_length=100, verbose_name='Erstellungs-Software')),
                ('status', models.CharField(choices=[('uploading', 'Wird hochgeladen'), ('processing', 'Wird verarbeitet'), ('ready', 'Bereit'), ('error', 'Fehler')], default='uploading', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'IFC Modell',
                'verbose_name_plural': 'IFC Modelle',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('ifc_guid', models.CharField(max_length=36, verbose_name='IFC GUID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Kurzbezeichnung')),
                ('elevation', models.FloatField(default=0, verbose_name='Höhe (m)')),
                ('sort_order', models.IntegerField(default=0)),
                ('ifc_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='ifc.ifcmodel', verbose_name='IFC Modell')),
            ],
            options={
                'verbose_name': 'Geschoss',
                'verbose_name_plural': 'Geschosse',
                'ordering': ['sort_order', 'elevation'],
            },
        ),
        migrations.CreateModel(
            name='IFCProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Same UUID as IFC MCP Backend', primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('name', models.CharField(max_length=255, verbose_name='Projektname')),
                ('mcp_project_id', models.UUIDField(blank=True, help_text='Reference to IFC MCP Backend', null=True, verbose_name='IFC MCP Projekt-ID')),
                ('cached_data', models.JSONField(blank=True, default=dict, help_text='Cached data from IFC MCP API', verbose_name='Cached Project Data')),
                ('cached_at', models.DateTimeField(blank=True, null=True, verbose_name='Cache Timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='UI User')),
            ],
            options={
                'verbose_name': 'IFC Projekt (Cache)',
                'verbose_name_plural': 'IFC Projekte (Cache)',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='ifcmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ifc.ifcproject', verbose_name='Projekt'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('ifc_guid', models.CharField(max_length=36, verbose_name='IFC GUID')),
                ('number', models.CharField(max_length=20, verbose_name='Raumnummer')),
                ('name', models.CharField(max_length=100, verbose_name='Raumname')),
                ('long_name', models.CharField(blank=True, max_length=255, verbose_name='Langname')),
                ('area', models.FloatField(default=0, verbose_name='Fläche (m²)')),
                ('height', models.FloatField(default=0, verbose_name='Höhe (m)')),
                ('volume', models.FloatField(default=0, verbose_name='Volumen (m³)')),
                ('perimeter', models.FloatField(default=0, verbose_name='Umfang (m)')),
                ('usage_category', models.CharField(blank=True, choices=[('NF1.1', 'NF 1.1 - Wohnen/Aufenthalt'), ('NF1.2', 'NF 1.2 - Büroarbeit'), ('NF1.3', 'NF 1.3 - Produktion'), ('NF2', 'NF 2 - Büroflächen'), ('NF3', 'NF 3 - Lager/Verteilen'), ('NF4', 'NF 4 - Bildung/Kultur'), ('NF5', 'NF 5 - Heilen/Pflegen'), ('NF6', 'NF 6 - Sonstige'), ('TF7', 'TF 7 - Technikflächen'), ('VF8', 'VF 8 - Verkehrsflächen')], max_length=10, verbose_name='Nutzungsart (DIN 277)')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='ifc.floor', verbose_name='Geschoss')),
                ('ifc_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='ifc.ifcmodel', verbose_name='IFC Modell')),
            ],
            options={
                'verbose_name': 'Raum',
                'verbose_name_plural': 'Räume',
                'ordering': ['floor__sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('ifc_guid', models.CharField(max_length=36, verbose_name='IFC GUID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Nummer')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Breite (m)')),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Höhe (m)')),
                ('door_type', models.CharField(blank=True, max_length=50, verbose_name='Türtyp')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('fire_rating', models.CharField(blank=True, max_length=20, verbose_name='Feuerwiderstand')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='IFC Properties')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doors', to='ifc.floor', verbose_name='Geschoss')),
                ('ifc_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='ifc.ifcmodel', verbose_name='IFC Modell')),
                ('from_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doors_from', to='ifc.room', verbose_name='Von Raum')),
                ('to_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doors_to', to='ifc.room', verbose_name='Nach Raum')),
            ],
            options={
                'verbose_name': 'Tür',
                'verbose_name_plural': 'Türen',
                'ordering': ['floor__sort_order', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Slab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('ifc_guid', models.CharField(max_length=36, verbose_name='IFC GUID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('slab_type', models.CharField(choices=[('FLOOR', 'Geschossdecke'), ('ROOF', 'Dach'), ('BASESLAB', 'Bodenplatte'), ('LANDING', 'Podest')], default='FLOOR', max_length=20, verbose_name='Typ')),
                ('area', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Fläche (m²)')),
                ('thickness', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Dicke (m)')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volumen (m³)')),
                ('perimeter', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Umfang (m)')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='IFC Properties')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slabs', to='ifc.floor', verbose_name='Geschoss')),
                ('ifc_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slabs', to='ifc.ifcmodel', verbose_name='IFC Modell')),
            ],
            options={
                'verbose_name': 'Decke/Platte',
                'verbose_name_plural': 'Decken/Platten',
                'ordering': ['floor__sort_order', 'slab_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('ifc_guid', models.CharField(max_length=36, verbose_name='IFC GUID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('length', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Länge (m)')),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Höhe (m)')),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Dicke (m)')),
                ('gross_area', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Bruttofläche (m²)')),
                ('net_area', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Nettofläche (m²)')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Volumen (m³)')),
                ('is_external', models.BooleanField(default=False, verbose_name='Außenwand')),
                ('is_load_bearing', models.BooleanField(default=False, verbose_name='Tragend')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='IFC Properties')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walls', to='ifc.floor', verbose_name='Geschoss')),
                ('ifc_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walls', to='ifc.ifcmodel', verbose_name='IFC Modell')),
            ],
            options={
                'verbose_name': 'Wand',
                'verbose_name_plural': 'Wände',
                'ordering': ['floor__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('ifc_guid', models.CharField(max_length=36, verbose_name='IFC GUID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Nummer')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('width', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Breite (m)')),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Höhe (m)')),
                ('area', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Fläche (m²)')),
                ('wall_position', models.CharField(blank=True, max_length=50, verbose_name='Wandposition')),
                ('elevation', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Höhe (m)')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('glazing_type', models.CharField(blank=True, max_length=100, verbose_name='Verglasungstyp')),
                ('u_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='U-Wert (W/m²K)')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='IFC Properties')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='windows', to='ifc.floor', verbose_name='Geschoss')),
                ('ifc_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='ifc.ifcmodel', verbose_name='IFC Modell')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='windows', to='ifc.room', verbose_name='Raum')),
            ],
            options={
                'verbose_name': 'Fenster',
                'verbose_name_plural': 'Fenster',
                'ordering': ['floor__sort_order', 'number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ifcmodel',
            unique_together={('project', 'version')},
        ),
    ]
