# Generated by Django 5.1.15 on 2026-02-19 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandschutzPruefung',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('titel', models.CharField(max_length=200)),
                ('projekt_name', models.CharField(max_length=200)),
                ('projekt_id', models.UUIDField(blank=True, null=True)),
                ('gebaeude_typ', models.CharField(blank=True, max_length=50)),
                ('etage', models.CharField(blank=True, default='EG', max_length=50)),
                ('flaeche_qm', models.FloatField(blank=True, null=True)),
                ('beschreibung', models.TextField(blank=True)),
                ('quelldatei', models.FileField(blank=True, null=True, upload_to='brandschutz/plaene/')),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='brandschutz/reports/')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('in_pruefung', 'In Prüfung'), ('abgeschlossen', 'Abgeschlossen'), ('maengel', 'Mängel festgestellt'), ('freigegeben', 'Freigegeben')], default='entwurf', max_length=50)),
                ('analyse_ergebnis', models.JSONField(blank=True, null=True)),
                ('pruefer', models.CharField(blank=True, max_length=200)),
                ('pruef_datum', models.DateField(blank=True, null=True)),
                ('naechste_pruefung', models.DateField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brandschutz-Prüfung',
                'verbose_name_plural': 'Brandschutz-Prüfungen',
                'ordering': ['-pruef_datum', '-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='BrandschutzRegelwerk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('kuerzel', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('asr', 'Arbeitsstättenregel'), ('din', 'DIN-Norm'), ('lbo', 'Landesbauordnung'), ('mbo', 'Musterbauordnung'), ('vstaettvo', 'Versammlungsstättenverordnung'), ('indbauril', 'Industriebaurichtlinie'), ('sonstige', 'Sonstige')], default='din', max_length=20)),
                ('kategorien', models.JSONField(default=list)),
                ('regeln', models.JSONField(default=dict)),
                ('url', models.URLField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('gueltig_ab', models.DateField(blank=True, null=True)),
                ('aktiv', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brandschutz-Regelwerk',
                'verbose_name_plural': 'Brandschutz-Regelwerke',
                'ordering': ['typ', 'kuerzel'],
            },
        ),
        migrations.CreateModel(
            name='BrandschutzSymbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('name', models.CharField(max_length=100)),
                ('din_nummer', models.CharField(max_length=20)),
                ('kategorie', models.CharField(choices=[('fluchtweg', 'Fluchtweg'), ('notausgang', 'Notausgang'), ('brandabschnitt', 'Brandabschnitt'), ('feuerloescher', 'Feuerlöscher'), ('rauchmelder', 'Rauchmelder'), ('sprinkler', 'Sprinkler'), ('rwa', 'RWA'), ('ex_zone', 'Ex-Zone'), ('brandmelder', 'Brandmelder'), ('hydrant', 'Hydrant')], default='feuerloescher', max_length=50)),
                ('beschreibung', models.TextField(blank=True)),
                ('block_dxf', models.FileField(blank=True, null=True, upload_to='brandschutz/symbole/')),
                ('block_json', models.JSONField(blank=True, null=True)),
                ('farbe', models.CharField(default='rot', max_length=20)),
                ('groesse_mm', models.FloatField(default=200)),
                ('regelwerk', models.CharField(blank=True, max_length=100)),
                ('aktiv', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brandschutz-Symbol',
                'verbose_name_plural': 'Brandschutz-Symbole',
                'ordering': ['kategorie', 'din_nummer'],
            },
        ),
        migrations.CreateModel(
            name='BrandschutzMangel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('kategorie', models.CharField(choices=[('fluchtweg', 'Fluchtweg'), ('notausgang', 'Notausgang'), ('brandabschnitt', 'Brandabschnitt'), ('feuerloescher', 'Feuerlöscher'), ('rauchmelder', 'Rauchmelder'), ('sprinkler', 'Sprinkler'), ('rwa', 'RWA'), ('ex_zone', 'Ex-Zone'), ('brandmelder', 'Brandmelder'), ('hydrant', 'Hydrant')], default='fluchtweg', max_length=50)),
                ('beschreibung', models.TextField()),
                ('schweregrad', models.CharField(choices=[('kritisch', 'Kritisch'), ('hoch', 'Hoch'), ('mittel', 'Mittel'), ('gering', 'Gering')], default='mittel', max_length=20)),
                ('regelwerk_referenz', models.CharField(blank=True, max_length=100)),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('behoben', models.BooleanField(default=False)),
                ('behoben_am', models.DateTimeField(blank=True, null=True)),
                ('behoben_kommentar', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='brandschutz/maengel/')),
                ('notizen', models.TextField(blank=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maengel', to='brandschutz.brandschutzpruefung')),
            ],
            options={
                'verbose_name': 'Brandschutz-Mangel',
                'verbose_name_plural': 'Brandschutz-Mängel',
                'ordering': ['-schweregrad', '-erstellt_am'],
            },
        ),
        migrations.CreateModel(
            name='BrandschutzSymbolVorschlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('symbol_typ', models.CharField(max_length=50)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('raum_referenz', models.CharField(blank=True, max_length=100)),
                ('begruendung', models.TextField(blank=True)),
                ('regelwerk_basis', models.CharField(blank=True, max_length=100)),
                ('prioritaet', models.IntegerField(default=2)),
                ('status', models.CharField(choices=[('vorgeschlagen', 'Vorgeschlagen'), ('genehmigt', 'Genehmigt'), ('abgelehnt', 'Abgelehnt'), ('eingefuegt', 'Eingefügt')], default='vorgeschlagen', max_length=20)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('pruefung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbole', to='brandschutz.brandschutzpruefung')),
            ],
            options={
                'verbose_name': 'Symbol-Vorschlag',
                'verbose_name_plural': 'Symbol-Vorschläge',
                'ordering': ['prioritaet', '-erstellt_am'],
            },
        ),
    ]
