# Generated by Django 5.2.6 on 2026-04-19 17:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_tenancy', '0003_remove_modulesubscription_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BerufsProfil',
            fields=[
                ('id', models.SlugField(help_text="z.B. 'brandschutz_sv', 'architekt'", primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Berufsbezeichnung')),
                ('icon', models.CharField(default='👤', max_length=10, verbose_name='Icon')),
                ('fokus', models.CharField(blank=True, help_text="z.B. 'Fluchtweg-Prüfung, Brandschutzkonzept'", max_length=200, verbose_name='Fachlicher Fokus')),
                ('bereitschaft', models.CharField(blank=True, help_text="z.B. '85% sofort'", max_length=100, verbose_name='Sofort-Bereitschaft')),
                ('install_command', models.TextField(blank=True, verbose_name='pip install Befehl')),
                ('yaml_config', models.TextField(blank=True, help_text='Fertiges YAML für dieses Berufsprofil', verbose_name='YAML-Konfiguration')),
                ('nlp_keywords', models.TextField(blank=True, help_text='Komma-getrennte Keywords für Intent-Klassifikation', verbose_name='NLP-Keywords')),
                ('report_template', models.CharField(blank=True, help_text="z.B. 'brandschutz_gutachten.jinja2'", max_length=100, verbose_name='Report-Template')),
                ('primary_output', models.CharField(blank=True, help_text="z.B. 'Brandschutz-Gutachten (PDF), Mängelprotokoll'", max_length=200, verbose_name='Primärer Output')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Berufsprofil',
                'verbose_name_plural': 'Berufsprofile',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('min_modules', models.PositiveIntegerField(default=3, verbose_name='Mind. Anzahl Module')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='Rabatt (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rabatt-Regel',
                'verbose_name_plural': 'Rabatt-Regeln',
                'ordering': ['min_modules'],
            },
        ),
        migrations.CreateModel(
            name='NL2CADModule',
            fields=[
                ('id', models.SlugField(help_text="URL-sicherer Bezeichner, z.B. 'brandschutz'", primary_key=True, serialize=False)),
                ('package', models.CharField(help_text="z.B. 'nl2cad-brandschutz'", max_length=120, unique=True, verbose_name='PyPI-Package-Name')),
                ('name', models.CharField(max_length=120, verbose_name='Anzeigename')),
                ('icon', models.CharField(default='📦', max_length=10, verbose_name='Icon (Emoji)')),
                ('color', models.CharField(default='#2563eb', max_length=7, verbose_name='Farbe (Hex)')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Kurzzeile')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('features', models.JSONField(default=list, help_text="Liste von Feature-Strings, z.B. ['DIN 277', 'WoFlV']", verbose_name='Features')),
                ('deps', models.JSONField(default=list, help_text="Liste von Package-IDs, z.B. ['nl2cad-core']", verbose_name='Abhängigkeiten')),
                ('norms', models.JSONField(default=list, help_text="z.B. ['DIN 277 (2016)', 'WoFlV 2004']", verbose_name='Regelwerke / Normen')),
                ('main_classes', models.JSONField(default=list, help_text="z.B. ['DIN277Calculator', 'WoFlVCalculator']", verbose_name='Wichtigste Klassen')),
                ('is_required', models.BooleanField(default=False, help_text='True für nl2cad-core — kann nicht abgewählt werden', verbose_name='Pflicht (immer aktiv)')),
                ('status', models.CharField(choices=[('stable', 'Stabil (produktiv)'), ('beta', 'Beta'), ('planned', 'In Planung'), ('deprecated', 'Veraltet')], db_index=True, default='planned', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('high', 'Hoch'), ('medium', 'Mittel'), ('low', 'Niedrig')], default='medium', max_length=10, verbose_name='Priorität')),
                ('story_points', models.PositiveIntegerField(default=0, verbose_name='Story Points')),
                ('target_quarter', models.CharField(blank=True, help_text="z.B. 'Q2/2026'", max_length=20, verbose_name='Ziel-Quartal')),
                ('adr_path', models.CharField(blank=True, help_text="Relativ zum Repo-Root, z.B. 'docs/adr/ADR-001-...'", max_length=255, verbose_name='ADR-Pfad')),
                ('workflow_path', models.CharField(blank=True, max_length=255, verbose_name='Workflow-Pfad')),
                ('pypi_url', models.URLField(blank=True, verbose_name='PyPI-URL')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'nl2cad-Modul',
                'verbose_name_plural': 'nl2cad-Module',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfilModuleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('vorhanden', '✅ Vorhanden'), ('konfiguration', '🔧 Nur Konfiguration nötig'), ('neu', '🔨 Neu-Entwicklung'), ('nicht', '— Nicht relevant')], default='neu', max_length=20, verbose_name='Mapping-Typ')),
                ('is_recommended', models.BooleanField(default=True, help_text='Wird im Konfigurator vorausgewählt', verbose_name='Empfohlen')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.nl2cadmodule')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.berufsprofil')),
            ],
            options={
                'verbose_name': 'Profil-Modul-Zuordnung',
                'verbose_name_plural': 'Profil-Modul-Zuordnungen',
                'ordering': ['profil', 'module__sort_order'],
                'unique_together': {('profil', 'module')},
            },
        ),
        migrations.AddField(
            model_name='berufsprofil',
            name='modules',
            field=models.ManyToManyField(related_name='berufsprofile', through='registry.ProfilModuleMapping', to='registry.nl2cadmodule', verbose_name='Module'),
        ),
        migrations.CreateModel(
            name='ModulePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('standard', 'Standard'), ('custom', 'Individuell (Tenant-spezifisch)'), ('free', 'Kostenlos')], default='standard', max_length=20, verbose_name='Preistyp')),
                ('setup_eur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Setup-Preis (€)')),
                ('monthly_eur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Monatspreis (€)')),
                ('label', models.CharField(blank=True, help_text="z.B. '79 € / Monat'", max_length=100, verbose_name='Preis-Label')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Gültig ab')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_module_pricing', to='django_tenancy.organization', verbose_name='Organisation (leer = Standard)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='registry.nl2cadmodule', verbose_name='Modul')),
            ],
            options={
                'verbose_name': 'Modul-Preis',
                'verbose_name_plural': 'Modul-Preise',
                'ordering': ['module', 'organization'],
                'indexes': [models.Index(fields=['module', 'organization'], name='registry_mo_module__1b1a5b_idx')],
                'unique_together': {('module', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(db_index=True, help_text='Multi-tenancy isolator')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend (Freigabe erwartet)'), ('trial', 'Test-Phase'), ('active', 'Aktiv'), ('suspended', 'Gesperrt'), ('cancelled', 'Gekündigt')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('monthly_eur', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Kann vom Standard-Preis abweichen (Custom Pricing)', max_digits=8, verbose_name='Aktueller Monatspreis (€)')),
                ('setup_eur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='Setup-Preis (€)')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Aktiviert am')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Gekündigt am')),
                ('trial_until', models.DateField(blank=True, null=True, verbose_name='Test-Phase bis')),
                ('approved_by', models.CharField(blank=True, max_length=100, verbose_name='Freigabe durch')),
                ('notes', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('berufsprofil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.berufsprofil', verbose_name='Berufsprofil (bei Onboarding gewählt)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='registry.nl2cadmodule', verbose_name='Modul')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_subscriptions', to='django_tenancy.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Modul-Subscription',
                'verbose_name_plural': 'Modul-Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='registry_te_tenant__7450f0_idx'), models.Index(fields=['organization', 'status'], name='registry_te_organiz_8e192c_idx')],
                'unique_together': {('organization', 'module')},
            },
        ),
    ]
