# Generated by Django 5.2.6 on 2026-04-19 15:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='modulepricing',
            new_name='registry_mo_module__1b1a5b_idx',
            old_name='registry_mo_module_i_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantsubscription',
            new_name='registry_te_tenant__7450f0_idx',
            old_name='registry_te_tenant__idx',
        ),
        migrations.RenameIndex(
            model_name='tenantsubscription',
            new_name='registry_te_organiz_8e192c_idx',
            old_name='registry_te_org_sta_idx',
        ),
        migrations.AlterField(
            model_name='berufsprofil',
            name='bereitschaft',
            field=models.CharField(blank=True, help_text="z.B. '85% sofort'", max_length=100, verbose_name='Sofort-Bereitschaft'),
        ),
        migrations.AlterField(
            model_name='berufsprofil',
            name='fokus',
            field=models.CharField(blank=True, help_text="z.B. 'Fluchtweg-Prüfung, Brandschutzkonzept'", max_length=200, verbose_name='Fachlicher Fokus'),
        ),
        migrations.AlterField(
            model_name='berufsprofil',
            name='id',
            field=models.SlugField(help_text="z.B. 'brandschutz_sv', 'architekt'", primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='berufsprofil',
            name='nlp_keywords',
            field=models.TextField(blank=True, help_text='Komma-getrennte Keywords für Intent-Klassifikation', verbose_name='NLP-Keywords'),
        ),
        migrations.AlterField(
            model_name='berufsprofil',
            name='primary_output',
            field=models.CharField(blank=True, help_text="z.B. 'Brandschutz-Gutachten (PDF), Mängelprotokoll'", max_length=200, verbose_name='Primärer Output'),
        ),
        migrations.AlterField(
            model_name='berufsprofil',
            name='report_template',
            field=models.CharField(blank=True, help_text="z.B. 'brandschutz_gutachten.jinja2'", max_length=100, verbose_name='Report-Template'),
        ),
        migrations.AlterField(
            model_name='berufsprofil',
            name='yaml_config',
            field=models.TextField(blank=True, help_text='Fertiges YAML für dieses Berufsprofil', verbose_name='YAML-Konfiguration'),
        ),
        migrations.AlterField(
            model_name='discountrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modulepricing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modulepricing',
            name='label',
            field=models.CharField(blank=True, help_text="z.B. '79 € / Monat'", max_length=100, verbose_name='Preis-Label'),
        ),
        migrations.AlterField(
            model_name='nl2cadmodule',
            name='adr_path',
            field=models.CharField(blank=True, help_text="Relativ zum Repo-Root, z.B. 'docs/adr/ADR-001-...'", max_length=255, verbose_name='ADR-Pfad'),
        ),
        migrations.AlterField(
            model_name='nl2cadmodule',
            name='deps',
            field=models.JSONField(default=list, help_text="Liste von Package-IDs, z.B. ['nl2cad-core']", verbose_name='Abhängigkeiten'),
        ),
        migrations.AlterField(
            model_name='nl2cadmodule',
            name='features',
            field=models.JSONField(default=list, help_text="Liste von Feature-Strings, z.B. ['DIN 277', 'WoFlV']", verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='nl2cadmodule',
            name='is_required',
            field=models.BooleanField(default=False, help_text='True für nl2cad-core — kann nicht abgewählt werden', verbose_name='Pflicht (immer aktiv)'),
        ),
        migrations.AlterField(
            model_name='nl2cadmodule',
            name='main_classes',
            field=models.JSONField(default=list, help_text="z.B. ['DIN277Calculator', 'WoFlVCalculator']", verbose_name='Wichtigste Klassen'),
        ),
        migrations.AlterField(
            model_name='nl2cadmodule',
            name='norms',
            field=models.JSONField(default=list, help_text="z.B. ['DIN 277 (2016)', 'WoFlV 2004']", verbose_name='Regelwerke / Normen'),
        ),
        migrations.AlterField(
            model_name='nl2cadmodule',
            name='package',
            field=models.CharField(help_text="z.B. 'nl2cad-brandschutz'", max_length=120, unique=True, verbose_name='PyPI-Package-Name'),
        ),
        migrations.AlterField(
            model_name='nl2cadmodule',
            name='target_quarter',
            field=models.CharField(blank=True, help_text="z.B. 'Q2/2026'", max_length=20, verbose_name='Ziel-Quartal'),
        ),
        migrations.AlterField(
            model_name='profilmodulemapping',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profilmodulemapping',
            name='is_recommended',
            field=models.BooleanField(default=True, help_text='Wird im Konfigurator vorausgewählt', verbose_name='Empfohlen'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='monthly_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Kann vom Standard-Preis abweichen (Custom Pricing)', max_digits=8, verbose_name='Aktueller Monatspreis (€)'),
        ),
        migrations.AlterModelTable(
            name='berufsprofil',
            table=None,
        ),
        migrations.AlterModelTable(
            name='discountrule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='modulepricing',
            table=None,
        ),
        migrations.AlterModelTable(
            name='nl2cadmodule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='profilmodulemapping',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tenantsubscription',
            table=None,
        ),
    ]
