name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    uses: iilgmbh/shared-ci/.github/workflows/_ci-python.yml@v1.0.1
    with:
      skip_tests: false
      django_settings_module: "config.settings.test"
    secrets: inherit
